baseurl = "http://alexisvincent.io"
languageCode = "en"
title = "alexisvincent.io"
theme = "hemingway"
copyright = "&copy; <a href=\"http://github.com/alexisvincent\">Alexis Vincent</a> 2017"
disqusShortname = "alexisjohnvincent"
googleAnalytics = ""
publishdir = "../"

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile", "javascript"]

[[params.social]]
url = "https://github.com/alexisvincent"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/vincent_alexis"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

